services:
  - type: web
    name: kmu-maintenance-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://your-frontend.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true