services:
  - type: web
    name: kmu-hostel-maintenance
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /
    autoDeploy: true 